name:                idid
version:             2.0.0
github:              "dbalan/idid"
license:             BSD3
author:              "Dhananjay Balan"
maintainer:          "idid@dbalan.in"
copyright:           "Dhananjay Balan"

extra-source-files:
- README.md
- ChangeLog.md

synopsis:            I did what?
category:            CLI

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/dbalan/idid#readme>

dependencies:
- base >= 4.7 && < 5
- optparse-applicative >= 0.14 && < 0.15
- time >= 1.8 && < 1.9
- directory >= 1.3 && < 1.4
- filepath >= 1.4 && <1.5

library:
  source-dirs: src

executables:
  idid:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - idid

tests:
  idid-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - idid
